# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b991cd3c29ef4a4b28fe394b38e91cf8e4f2cd76eef532d478b511016b1295ee8f68cd5d47aeb42afbf9557f88f5e4319f6b553c6359478932d1aec64303c2ec

test:
  secret_key_base: 671fba4b53fbdda1fea397eb6b570e9f9e32b8215deba97726a49ba232babb0d2fecb2fe272c1b4c207ba96dfd642c07e1db30412239b40b6d937052b200709c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
